=== JeroenDeDeken/KTV_MastersOfCode/mastersofcode-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/moc_metadata_0.3.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="assignment">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="participants"/>
              <xs:element type="xs:string" name="spectators"/>
              <xs:element name="creator">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="organisation"/>
                    <xs:element type="xs:anyURI" name="link"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="files">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="file" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="path" use="required"/>
                      <xs:attribute type="xs:boolean" name="write" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="tests">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="test" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="required"/>
                      <xs:attribute type="xs:string" name="description" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="hints">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hint" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="text" use="required"/>
                      <xs:attribute type="xs:short" name="time" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JeroenDeDeken/KTV_MastersOfCode/mastersofcode-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/assignment.xml
<?xml version="1.0" encoding="UTF-8"?>
<assignment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./moc_metadata_0.3.xsd">
	<metadata>
		<name>Assignment name</name>
		<participants>Description for participants</participants>
		<spectators>Description for spectators</spectators>
		<creator>
			<name>Creator name</name>
			<organisation>Creator organisation</organisation>
			<link>http://localhost</link>
		</creator>
	</metadata>
	<files>
		<file path="src/main/java/nl/mok/App1.java" write="true" />
		<file path="src/main/java/nl/mok/App2.java" write="false" />
	</files>
	<tests>
		<test name="Test1" description="Test description" />
		<test name="Test2" description="Test description" />
	</tests>
	<hints>
		<hint text="Hint 1" time="100" />
		<hint text="Hint 2" time="200" />
	</hints>
</assignment>
